FROM python:3.11-bookworm

RUN pip install pypush srp cryptography requests pbkdf2 pycryptodomex flask

WORKDIR /app
COPY . .

# EXPOSE 3033

RUN pip install debugpy

CMD ["python", "-m", "debugpy", "--listen", "0.0.0.0:5679", "server.py"]