services:
  findmy:
    build: 
      context: .
      dockerfile: Dockerfile.debug
    image: findmy_docker-debug
    container_name: findmy_server
    stop_grace_period: 1s
    logging:
        driver: "json-file"
        options:
            max-file: 5
            max-size: 10m
    volumes:
      - ./data:/app/data:Z
      - ./templates:/app/templates
    ports:
      - 3033:3033
      - 5679:5679
  anisette:
    image: dadoum/anisette-v3-server
    container_name: findmy_anisette
    network_mode: 'service:findmy'
    stop_grace_period: 1s
    logging:
        driver: "json-file"
        options:
            max-file: 5
            max-size: 10m
    volumes:
      - anisette-v3_data:/home/Alcoholic/.config/anisette-v3/lib:Z

volumes:
  anisette-v3_data: